import { fileURLToPath } from 'node:url';

/** SQL migrations generated by drizzle-kit (`pnpm db:generate`). */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../../drizzle', import.meta.url));
