// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/pairing.dart';
import 'api/session.dart';
import 'api/sharing.dart';
import 'api/vault.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 618273093;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_zvault_mobile',
        ioDirectory: '../../crates/zvault-mobile/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiVaultEntryOpen({
    required String projectId,
    required String kind,
    required String id,
    required String blobJson,
  });

  Future<EnvironmentView> crateApiVaultEnvironmentOpen({
    required String projectId,
    required String entryJson,
    String? memberWrapJson,
  });

  Future<void> crateApiInitApp();

  Future<ItemDetail> crateApiVaultItemOpen({
    required String vaultId,
    required String recordJson,
  });

  Future<ItemSummary> crateApiVaultItemSummary({
    required String vaultId,
    required String recordJson,
  });

  Future<OneTimeCode?> crateApiVaultItemTotp({
    required String vaultId,
    required String recordJson,
    required PlatformInt64 unixSecs,
  });

  void crateApiSessionLock();

  void crateApiPairingPairingCancel();

  Future<PairedAccount> crateApiPairingPairingFinish({
    required String ephemeralPublicKey,
    required String nonce,
    required String ct,
  });

  Future<ScannedCode> crateApiPairingPairingScan({required String uri});

  Future<String> crateApiVaultProjectOpen({
    required String recordJson,
    String? memberWrapJson,
  });

  Future<String> crateApiVaultSecretValueOpen({
    required String projectId,
    required String secretId,
    required String environmentId,
    required String blobJson,
  });

  Future<NewShareLink> crateApiSharingShareLinkCreate({
    required String vaultId,
    required String recordJson,
    required String shareOrigin,
  });

  Future<NewUserShare> crateApiSharingShareSealTo({
    required String vaultId,
    required String recordJson,
    required String recipientPublicKey,
  });

  Future<String> crateApiSharingSharingFingerprint({required String publicKey});

  Future<SharingIdentity> crateApiSharingSharingIdentity();

  Future<void> crateApiSessionUnlock({
    required String email,
    required String keyset,
  });

  String? crateApiSessionUnlockedEmail();

  Future<VaultSummary> crateApiVaultVaultOpen({required String recordJson});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiVaultEntryOpen({
    required String projectId,
    required String kind,
    required String id,
    required String blobJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_String(kind, serializer);
          sse_encode_String(id, serializer);
          sse_encode_String(blobJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultEntryOpenConstMeta,
        argValues: [projectId, kind, id, blobJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultEntryOpenConstMeta => const TaskConstMeta(
    debugName: "entry_open",
    argNames: ["projectId", "kind", "id", "blobJson"],
  );

  @override
  Future<EnvironmentView> crateApiVaultEnvironmentOpen({
    required String projectId,
    required String entryJson,
    String? memberWrapJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_String(entryJson, serializer);
          sse_encode_opt_String(memberWrapJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_environment_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultEnvironmentOpenConstMeta,
        argValues: [projectId, entryJson, memberWrapJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultEnvironmentOpenConstMeta =>
      const TaskConstMeta(
        debugName: "environment_open",
        argNames: ["projectId", "entryJson", "memberWrapJson"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<ItemDetail> crateApiVaultItemOpen({
    required String vaultId,
    required String recordJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultId, serializer);
          sse_encode_String(recordJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_item_detail,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultItemOpenConstMeta,
        argValues: [vaultId, recordJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultItemOpenConstMeta => const TaskConstMeta(
    debugName: "item_open",
    argNames: ["vaultId", "recordJson"],
  );

  @override
  Future<ItemSummary> crateApiVaultItemSummary({
    required String vaultId,
    required String recordJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultId, serializer);
          sse_encode_String(recordJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_item_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultItemSummaryConstMeta,
        argValues: [vaultId, recordJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultItemSummaryConstMeta => const TaskConstMeta(
    debugName: "item_summary",
    argNames: ["vaultId", "recordJson"],
  );

  @override
  Future<OneTimeCode?> crateApiVaultItemTotp({
    required String vaultId,
    required String recordJson,
    required PlatformInt64 unixSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultId, serializer);
          sse_encode_String(recordJson, serializer);
          sse_encode_i_64(unixSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_one_time_code,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultItemTotpConstMeta,
        argValues: [vaultId, recordJson, unixSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultItemTotpConstMeta => const TaskConstMeta(
    debugName: "item_totp",
    argNames: ["vaultId", "recordJson", "unixSecs"],
  );

  @override
  void crateApiSessionLock() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionLockConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionLockConstMeta =>
      const TaskConstMeta(debugName: "lock", argNames: []);

  @override
  void crateApiPairingPairingCancel() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPairingPairingCancelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingPairingCancelConstMeta =>
      const TaskConstMeta(debugName: "pairing_cancel", argNames: []);

  @override
  Future<PairedAccount> crateApiPairingPairingFinish({
    required String ephemeralPublicKey,
    required String nonce,
    required String ct,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ephemeralPublicKey, serializer);
          sse_encode_String(nonce, serializer);
          sse_encode_String(ct, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_paired_account,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPairingPairingFinishConstMeta,
        argValues: [ephemeralPublicKey, nonce, ct],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingPairingFinishConstMeta =>
      const TaskConstMeta(
        debugName: "pairing_finish",
        argNames: ["ephemeralPublicKey", "nonce", "ct"],
      );

  @override
  Future<ScannedCode> crateApiPairingPairingScan({required String uri}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uri, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scanned_code,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPairingPairingScanConstMeta,
        argValues: [uri],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPairingPairingScanConstMeta =>
      const TaskConstMeta(debugName: "pairing_scan", argNames: ["uri"]);

  @override
  Future<String> crateApiVaultProjectOpen({
    required String recordJson,
    String? memberWrapJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(recordJson, serializer);
          sse_encode_opt_String(memberWrapJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultProjectOpenConstMeta,
        argValues: [recordJson, memberWrapJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultProjectOpenConstMeta => const TaskConstMeta(
    debugName: "project_open",
    argNames: ["recordJson", "memberWrapJson"],
  );

  @override
  Future<String> crateApiVaultSecretValueOpen({
    required String projectId,
    required String secretId,
    required String environmentId,
    required String blobJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectId, serializer);
          sse_encode_String(secretId, serializer);
          sse_encode_String(environmentId, serializer);
          sse_encode_String(blobJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultSecretValueOpenConstMeta,
        argValues: [projectId, secretId, environmentId, blobJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultSecretValueOpenConstMeta =>
      const TaskConstMeta(
        debugName: "secret_value_open",
        argNames: ["projectId", "secretId", "environmentId", "blobJson"],
      );

  @override
  Future<NewShareLink> crateApiSharingShareLinkCreate({
    required String vaultId,
    required String recordJson,
    required String shareOrigin,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultId, serializer);
          sse_encode_String(recordJson, serializer);
          sse_encode_String(shareOrigin, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_new_share_link,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSharingShareLinkCreateConstMeta,
        argValues: [vaultId, recordJson, shareOrigin],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSharingShareLinkCreateConstMeta =>
      const TaskConstMeta(
        debugName: "share_link_create",
        argNames: ["vaultId", "recordJson", "shareOrigin"],
      );

  @override
  Future<NewUserShare> crateApiSharingShareSealTo({
    required String vaultId,
    required String recordJson,
    required String recipientPublicKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultId, serializer);
          sse_encode_String(recordJson, serializer);
          sse_encode_String(recipientPublicKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_new_user_share,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSharingShareSealToConstMeta,
        argValues: [vaultId, recordJson, recipientPublicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSharingShareSealToConstMeta => const TaskConstMeta(
    debugName: "share_seal_to",
    argNames: ["vaultId", "recordJson", "recipientPublicKey"],
  );

  @override
  Future<String> crateApiSharingSharingFingerprint({
    required String publicKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(publicKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSharingSharingFingerprintConstMeta,
        argValues: [publicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSharingSharingFingerprintConstMeta =>
      const TaskConstMeta(
        debugName: "sharing_fingerprint",
        argNames: ["publicKey"],
      );

  @override
  Future<SharingIdentity> crateApiSharingSharingIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sharing_identity,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSharingSharingIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSharingSharingIdentityConstMeta =>
      const TaskConstMeta(debugName: "sharing_identity", argNames: []);

  @override
  Future<void> crateApiSessionUnlock({
    required String email,
    required String keyset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(email, serializer);
          sse_encode_String(keyset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSessionUnlockConstMeta,
        argValues: [email, keyset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionUnlockConstMeta =>
      const TaskConstMeta(debugName: "unlock", argNames: ["email", "keyset"]);

  @override
  String? crateApiSessionUnlockedEmail() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSessionUnlockedEmailConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionUnlockedEmailConstMeta =>
      const TaskConstMeta(debugName: "unlocked_email", argNames: []);

  @override
  Future<VaultSummary> crateApiVaultVaultOpen({required String recordJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(recordJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vault_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiVaultVaultOpenConstMeta,
        argValues: [recordJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVaultVaultOpenConstMeta =>
      const TaskConstMeta(debugName: "vault_open", argNames: ["recordJson"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  OneTimeCode dco_decode_box_autoadd_one_time_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_one_time_code(raw);
  }

  @protected
  EnvironmentView dco_decode_environment_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EnvironmentView(
      metaJson: dco_decode_String(arr[0]),
      unlocked: dco_decode_bool(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ItemDetail dco_decode_item_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ItemDetail(
      title: dco_decode_String(arr[0]),
      username: dco_decode_String(arr[1]),
      password: dco_decode_String(arr[2]),
      urls: dco_decode_list_String(arr[3]),
      notes: dco_decode_String(arr[4]),
      hasTotp: dco_decode_bool(arr[5]),
    );
  }

  @protected
  ItemSummary dco_decode_item_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ItemSummary(
      title: dco_decode_String(arr[0]),
      username: dco_decode_String(arr[1]),
      url: dco_decode_opt_String(arr[2]),
      hasTotp: dco_decode_bool(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NewShareLink dco_decode_new_share_link(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NewShareLink(
      id: dco_decode_String(arr[0]),
      verifier: dco_decode_String(arr[1]),
      blobJson: dco_decode_String(arr[2]),
      url: dco_decode_String(arr[3]),
    );
  }

  @protected
  NewUserShare dco_decode_new_user_share(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NewUserShare(
      id: dco_decode_String(arr[0]),
      senderPublicKey: dco_decode_String(arr[1]),
      ephemeralPublicKey: dco_decode_String(arr[2]),
      blobJson: dco_decode_String(arr[3]),
    );
  }

  @protected
  OneTimeCode dco_decode_one_time_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return OneTimeCode(
      code: dco_decode_String(arr[0]),
      period: dco_decode_u_32(arr[1]),
      remaining: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  OneTimeCode? dco_decode_opt_box_autoadd_one_time_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_one_time_code(raw);
  }

  @protected
  PairedAccount dco_decode_paired_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PairedAccount(
      email: dco_decode_String(arr[0]),
      keyset: dco_decode_String(arr[1]),
    );
  }

  @protected
  ScannedCode dco_decode_scanned_code(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ScannedCode(
      api: dco_decode_String(arr[0]),
      pairingId: dco_decode_String(arr[1]),
      claimToken: dco_decode_String(arr[2]),
      publicKey: dco_decode_String(arr[3]),
      code: dco_decode_String(arr[4]),
    );
  }

  @protected
  SharingIdentity dco_decode_sharing_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SharingIdentity(
      publicKey: dco_decode_String(arr[0]),
      fingerprint: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VaultSummary dco_decode_vault_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return VaultSummary(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  OneTimeCode sse_decode_box_autoadd_one_time_code(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_one_time_code(deserializer));
  }

  @protected
  EnvironmentView sse_decode_environment_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_metaJson = sse_decode_String(deserializer);
    var var_unlocked = sse_decode_bool(deserializer);
    return EnvironmentView(metaJson: var_metaJson, unlocked: var_unlocked);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ItemDetail sse_decode_item_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_urls = sse_decode_list_String(deserializer);
    var var_notes = sse_decode_String(deserializer);
    var var_hasTotp = sse_decode_bool(deserializer);
    return ItemDetail(
      title: var_title,
      username: var_username,
      password: var_password,
      urls: var_urls,
      notes: var_notes,
      hasTotp: var_hasTotp,
    );
  }

  @protected
  ItemSummary sse_decode_item_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_url = sse_decode_opt_String(deserializer);
    var var_hasTotp = sse_decode_bool(deserializer);
    return ItemSummary(
      title: var_title,
      username: var_username,
      url: var_url,
      hasTotp: var_hasTotp,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NewShareLink sse_decode_new_share_link(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_verifier = sse_decode_String(deserializer);
    var var_blobJson = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    return NewShareLink(
      id: var_id,
      verifier: var_verifier,
      blobJson: var_blobJson,
      url: var_url,
    );
  }

  @protected
  NewUserShare sse_decode_new_user_share(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_senderPublicKey = sse_decode_String(deserializer);
    var var_ephemeralPublicKey = sse_decode_String(deserializer);
    var var_blobJson = sse_decode_String(deserializer);
    return NewUserShare(
      id: var_id,
      senderPublicKey: var_senderPublicKey,
      ephemeralPublicKey: var_ephemeralPublicKey,
      blobJson: var_blobJson,
    );
  }

  @protected
  OneTimeCode sse_decode_one_time_code(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_period = sse_decode_u_32(deserializer);
    var var_remaining = sse_decode_u_32(deserializer);
    return OneTimeCode(
      code: var_code,
      period: var_period,
      remaining: var_remaining,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OneTimeCode? sse_decode_opt_box_autoadd_one_time_code(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_one_time_code(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PairedAccount sse_decode_paired_account(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_email = sse_decode_String(deserializer);
    var var_keyset = sse_decode_String(deserializer);
    return PairedAccount(email: var_email, keyset: var_keyset);
  }

  @protected
  ScannedCode sse_decode_scanned_code(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_api = sse_decode_String(deserializer);
    var var_pairingId = sse_decode_String(deserializer);
    var var_claimToken = sse_decode_String(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_code = sse_decode_String(deserializer);
    return ScannedCode(
      api: var_api,
      pairingId: var_pairingId,
      claimToken: var_claimToken,
      publicKey: var_publicKey,
      code: var_code,
    );
  }

  @protected
  SharingIdentity sse_decode_sharing_identity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_String(deserializer);
    var var_fingerprint = sse_decode_String(deserializer);
    return SharingIdentity(
      publicKey: var_publicKey,
      fingerprint: var_fingerprint,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VaultSummary sse_decode_vault_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return VaultSummary(id: var_id, name: var_name);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_one_time_code(
    OneTimeCode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_one_time_code(self, serializer);
  }

  @protected
  void sse_encode_environment_view(
    EnvironmentView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.metaJson, serializer);
    sse_encode_bool(self.unlocked, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_item_detail(ItemDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_list_String(self.urls, serializer);
    sse_encode_String(self.notes, serializer);
    sse_encode_bool(self.hasTotp, serializer);
  }

  @protected
  void sse_encode_item_summary(ItemSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_opt_String(self.url, serializer);
    sse_encode_bool(self.hasTotp, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_new_share_link(NewShareLink self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.verifier, serializer);
    sse_encode_String(self.blobJson, serializer);
    sse_encode_String(self.url, serializer);
  }

  @protected
  void sse_encode_new_user_share(NewUserShare self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.senderPublicKey, serializer);
    sse_encode_String(self.ephemeralPublicKey, serializer);
    sse_encode_String(self.blobJson, serializer);
  }

  @protected
  void sse_encode_one_time_code(OneTimeCode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_u_32(self.period, serializer);
    sse_encode_u_32(self.remaining, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_one_time_code(
    OneTimeCode? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_one_time_code(self, serializer);
    }
  }

  @protected
  void sse_encode_paired_account(PairedAccount self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.email, serializer);
    sse_encode_String(self.keyset, serializer);
  }

  @protected
  void sse_encode_scanned_code(ScannedCode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.api, serializer);
    sse_encode_String(self.pairingId, serializer);
    sse_encode_String(self.claimToken, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.code, serializer);
  }

  @protected
  void sse_encode_sharing_identity(
    SharingIdentity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.fingerprint, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vault_summary(VaultSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
