// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/pairing.dart';
import 'api/session.dart';
import 'api/sharing.dart';
import 'api/vault.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  OneTimeCode dco_decode_box_autoadd_one_time_code(dynamic raw);

  @protected
  SecretShare dco_decode_box_autoadd_secret_share(dynamic raw);

  @protected
  EnvironmentView dco_decode_environment_view(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ItemDetail dco_decode_item_detail(dynamic raw);

  @protected
  ItemSummary dco_decode_item_summary(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NewShareLink dco_decode_new_share_link(dynamic raw);

  @protected
  NewUserShare dco_decode_new_user_share(dynamic raw);

  @protected
  OneTimeCode dco_decode_one_time_code(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  OneTimeCode? dco_decode_opt_box_autoadd_one_time_code(dynamic raw);

  @protected
  PairedAccount dco_decode_paired_account(dynamic raw);

  @protected
  ScannedCode dco_decode_scanned_code(dynamic raw);

  @protected
  SecretShare dco_decode_secret_share(dynamic raw);

  @protected
  SharingIdentity dco_decode_sharing_identity(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VaultSummary dco_decode_vault_summary(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  OneTimeCode sse_decode_box_autoadd_one_time_code(
    SseDeserializer deserializer,
  );

  @protected
  SecretShare sse_decode_box_autoadd_secret_share(SseDeserializer deserializer);

  @protected
  EnvironmentView sse_decode_environment_view(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ItemDetail sse_decode_item_detail(SseDeserializer deserializer);

  @protected
  ItemSummary sse_decode_item_summary(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NewShareLink sse_decode_new_share_link(SseDeserializer deserializer);

  @protected
  NewUserShare sse_decode_new_user_share(SseDeserializer deserializer);

  @protected
  OneTimeCode sse_decode_one_time_code(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  OneTimeCode? sse_decode_opt_box_autoadd_one_time_code(
    SseDeserializer deserializer,
  );

  @protected
  PairedAccount sse_decode_paired_account(SseDeserializer deserializer);

  @protected
  ScannedCode sse_decode_scanned_code(SseDeserializer deserializer);

  @protected
  SecretShare sse_decode_secret_share(SseDeserializer deserializer);

  @protected
  SharingIdentity sse_decode_sharing_identity(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VaultSummary sse_decode_vault_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_one_time_code(
    OneTimeCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_secret_share(
    SecretShare self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_environment_view(
    EnvironmentView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_item_detail(ItemDetail self, SseSerializer serializer);

  @protected
  void sse_encode_item_summary(ItemSummary self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_new_share_link(NewShareLink self, SseSerializer serializer);

  @protected
  void sse_encode_new_user_share(NewUserShare self, SseSerializer serializer);

  @protected
  void sse_encode_one_time_code(OneTimeCode self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_one_time_code(
    OneTimeCode? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_paired_account(PairedAccount self, SseSerializer serializer);

  @protected
  void sse_encode_scanned_code(ScannedCode self, SseSerializer serializer);

  @protected
  void sse_encode_secret_share(SecretShare self, SseSerializer serializer);

  @protected
  void sse_encode_sharing_identity(
    SharingIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vault_summary(VaultSummary self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
