import { z } from 'zod';
import { EncryptedBlob } from './crypto.js';

/**
 * Vault and item contracts. The server stores these records but only ever
 * sees ciphertext: item titles, usernames, passwords, URLs and notes are all
 * inside `encryptedData`, sealed on the client with a per-item key.
 *
 * Ids are UUIDs generated by the client, because each ciphertext is bound to
 * its vault and item id before it is uploaded.
 */

export const RecordId = z.uuid();
export type RecordId = z.infer<typeof RecordId>;

/** Wrapped 32-byte key: 48 bytes of ciphertext including the tag. */
const WrappedKey = EncryptedBlob.refine((b) => b.ct.length === 64, {
  message: 'must be a wrapped 32-byte key',
});

/** Largest encrypted item accepted, as base64url characters (~96 KiB). */
export const MAX_ITEM_CT_CHARS = 128 * 1024;
const ItemData = EncryptedBlob.refine((b) => b.ct.length <= MAX_ITEM_CT_CHARS, {
  message: 'item is too large',
});

export const VaultRecord = z.object({
  id: RecordId,
  /** Vault key wrapped by the account key; `kid` is `account`. */
  encryptedKey: WrappedKey,
  /** Vault name and other metadata, sealed with the vault key. */
  encryptedMeta: ItemData,
  createdAt: z.iso.datetime(),
});
export type VaultRecord = z.infer<typeof VaultRecord>;

export const CreateVaultRequest = VaultRecord.pick({
  id: true,
  encryptedKey: true,
  encryptedMeta: true,
});
export type CreateVaultRequest = z.infer<typeof CreateVaultRequest>;

export const ListVaultsResponse = z.object({ vaults: z.array(VaultRecord) });
export type ListVaultsResponse = z.infer<typeof ListVaultsResponse>;

const ItemBase = z.object({
  id: RecordId,
  vaultId: RecordId,
  /** Increases by one on every write; used for optimistic concurrency. */
  revision: z.number().int().min(1),
  /** Vault-wide change sequence number; used as the sync cursor. */
  seq: z.number().int().min(1),
  updatedAt: z.iso.datetime(),
});

export const LiveItemRecord = ItemBase.extend({
  deleted: z.literal(false),
  /** Item key wrapped by the vault key; `kid` is the vault id. */
  encryptedKey: WrappedKey,
  /** Item fields sealed with the item key; `kid` is the item id. */
  encryptedData: ItemData,
});

/** A deleted item. Kept so other devices learn about the deletion on sync. */
export const DeletedItemRecord = ItemBase.extend({ deleted: z.literal(true) });

export const ItemRecord = z.discriminatedUnion('deleted', [LiveItemRecord, DeletedItemRecord]);
export type ItemRecord = z.infer<typeof ItemRecord>;
export type LiveItemRecord = z.infer<typeof LiveItemRecord>;

/**
 * Creates or replaces an item. `baseRevision` is the revision the client
 * edited (0 to create); the server rejects the write with 409 and returns the
 * current record if someone else changed it first.
 */
export const PutItemRequest = z.object({
  baseRevision: z.number().int().min(0),
  encryptedKey: WrappedKey,
  encryptedData: ItemData,
});
export type PutItemRequest = z.infer<typeof PutItemRequest>;

export const DeleteItemQuery = z.object({
  baseRevision: z.coerce.number().int().min(1),
});

export const MAX_SYNC_PAGE = 500;

export const SyncItemsQuery = z.object({
  /** Return changes after this cursor; 0 for a full sync. */
  since: z.coerce.number().int().min(0).default(0),
  limit: z.coerce.number().int().min(1).max(MAX_SYNC_PAGE).default(MAX_SYNC_PAGE),
});

export const SyncItemsResponse = z.object({
  items: z.array(ItemRecord),
  /** Pass back as `since` on the next call. */
  cursor: z.number().int().min(0),
  hasMore: z.boolean(),
});
export type SyncItemsResponse = z.infer<typeof SyncItemsResponse>;

export const ItemConflictResponse = z.object({
  error: z.literal('conflict'),
  current: ItemRecord,
});
export type ItemConflictResponse = z.infer<typeof ItemConflictResponse>;
