// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pending`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `GrantPlaintext`, `Pending`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// Reads a scanned (or pasted) QR code and makes this phone's one-time key.
Future<ScannedCode> pairingScan({required String uri}) =>
    RustLib.instance.api.crateApiPairingPairingScan(uri: uri);

/// Opens the grant the Mac sealed to this phone and unlocks with it.
Future<PairedAccount> pairingFinish({
  required String ephemeralPublicKey,
  required String nonce,
  required String ct,
}) => RustLib.instance.api.crateApiPairingPairingFinish(
  ephemeralPublicKey: ephemeralPublicKey,
  nonce: nonce,
  ct: ct,
);

/// Forgets a scan that won't be finished.
void pairingCancel() => RustLib.instance.api.crateApiPairingPairingCancel();

/// The account the Mac handed over.
class PairedAccount {
  final String email;

  /// The account keyset, for the app's biometric-protected store. It unlocks
  /// everything this account can see.
  final String keyset;

  const PairedAccount({required this.email, required this.keyset});

  @override
  int get hashCode => email.hashCode ^ keyset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairedAccount &&
          runtimeType == other.runtimeType &&
          email == other.email &&
          keyset == other.keyset;
}

/// What a scan gives the app to call the server with and to show.
class ScannedCode {
  /// API origin from the QR code.
  final String api;
  final String pairingId;

  /// Proves to the server that this phone saw the QR code.
  final String claimToken;

  /// This phone's one-time public key.
  final String publicKey;

  /// Six digits the Mac shows too.
  final String code;

  const ScannedCode({
    required this.api,
    required this.pairingId,
    required this.claimToken,
    required this.publicKey,
    required this.code,
  });

  @override
  int get hashCode =>
      api.hashCode ^
      pairingId.hashCode ^
      claimToken.hashCode ^
      publicKey.hashCode ^
      code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScannedCode &&
          runtimeType == other.runtimeType &&
          api == other.api &&
          pairingId == other.pairingId &&
          claimToken == other.claimToken &&
          publicKey == other.publicKey &&
          code == other.code;
}
