// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Unlocks with the keyset the phone kept in its biometric-protected store.
Future<void> unlock({required String email, required String keyset}) =>
    RustLib.instance.api.crateApiSessionUnlock(email: email, keyset: keyset);

/// Wipes every key.
void lock() => RustLib.instance.api.crateApiSessionLock();

/// The unlocked account's email, or None while locked.
String? unlockedEmail() => RustLib.instance.api.crateApiSessionUnlockedEmail();
