// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blob_json`, `check_origin`, `open_payload`, `open_secret_payload`, `payload`, `seal_box`, `seal_link`, `secret_payload`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Payload`, `SecretOrigin`, `WireBlob`

/// Encrypts an item under a fresh link key and builds its URL on
/// `share_origin` (the share page, such as `https://host/share`).
Future<NewShareLink> shareLinkCreate({
  required String vaultId,
  required String recordJson,
  required String shareOrigin,
}) => RustLib.instance.api.crateApiSharingShareLinkCreate(
  vaultId: vaultId,
  recordJson: recordJson,
  shareOrigin: shareOrigin,
);

/// Encrypts one project secret's value under a fresh link key.
Future<NewShareLink> secretShareLinkCreate({
  required SecretShare secret,
  required String shareOrigin,
}) => RustLib.instance.api.crateApiSharingSecretShareLinkCreate(
  secret: secret,
  shareOrigin: shareOrigin,
);

/// Encrypts one project secret's value to another user's sharing key.
Future<NewUserShare> secretShareSealTo({
  required SecretShare secret,
  required String recipientPublicKey,
}) => RustLib.instance.api.crateApiSharingSecretShareSealTo(
  secret: secret,
  recipientPublicKey: recipientPublicKey,
);

/// This account's sharing public key, to publish before sending a share.
Future<SharingIdentity> sharingIdentity() =>
    RustLib.instance.api.crateApiSharingSharingIdentity();

/// Someone else's security code, for comparing out of band.
Future<String> sharingFingerprint({required String publicKey}) => RustLib
    .instance
    .api
    .crateApiSharingSharingFingerprint(publicKey: publicKey);

/// Encrypts an item to another user's sharing key.
Future<NewUserShare> shareSealTo({
  required String vaultId,
  required String recordJson,
  required String recipientPublicKey,
}) => RustLib.instance.api.crateApiSharingShareSealTo(
  vaultId: vaultId,
  recordJson: recordJson,
  recipientPublicKey: recipientPublicKey,
);

/// A link ready to register with `POST /shares/links`.
class NewShareLink {
  final String id;
  final String verifier;

  /// `EncryptedBlob` as JSON.
  final String blobJson;

  /// Carries the link key in its fragment. Show and share it; never send it
  /// to the API.
  final String url;

  const NewShareLink({
    required this.id,
    required this.verifier,
    required this.blobJson,
    required this.url,
  });

  @override
  int get hashCode =>
      id.hashCode ^ verifier.hashCode ^ blobJson.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewShareLink &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          verifier == other.verifier &&
          blobJson == other.blobJson &&
          url == other.url;
}

/// A share sealed to another user, ready for `POST /shares/users`.
class NewUserShare {
  final String id;
  final String senderPublicKey;
  final String ephemeralPublicKey;

  /// `EncryptedBlob` as JSON.
  final String blobJson;

  const NewUserShare({
    required this.id,
    required this.senderPublicKey,
    required this.ephemeralPublicKey,
    required this.blobJson,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      senderPublicKey.hashCode ^
      ephemeralPublicKey.hashCode ^
      blobJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewUserShare &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderPublicKey == other.senderPublicKey &&
          ephemeralPublicKey == other.ephemeralPublicKey &&
          blobJson == other.blobJson;
}

/// One project secret's value in one environment, to share. The value is
/// opened here; the rest is its already-open metadata, for the recipient.
class SecretShare {
  final String projectId;
  final String secretId;
  final String environmentId;

  /// The sealed value, as `EncryptedBlob` JSON.
  final String valueJson;
  final String name;
  final String key;
  final String note;
  final String projectName;
  final String environmentName;

  const SecretShare({
    required this.projectId,
    required this.secretId,
    required this.environmentId,
    required this.valueJson,
    required this.name,
    required this.key,
    required this.note,
    required this.projectName,
    required this.environmentName,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      secretId.hashCode ^
      environmentId.hashCode ^
      valueJson.hashCode ^
      name.hashCode ^
      key.hashCode ^
      note.hashCode ^
      projectName.hashCode ^
      environmentName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecretShare &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          secretId == other.secretId &&
          environmentId == other.environmentId &&
          valueJson == other.valueJson &&
          name == other.name &&
          key == other.key &&
          note == other.note &&
          projectName == other.projectName &&
          environmentName == other.environmentName;
}

class SharingIdentity {
  final String publicKey;
  final String fingerprint;

  const SharingIdentity({required this.publicKey, required this.fingerprint});

  @override
  int get hashCode => publicKey.hashCode ^ fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SharingIdentity &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          fingerprint == other.fingerprint;
}
