// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<VaultSummary> vaultOpen({required String recordJson}) =>
    RustLib.instance.api.crateApiVaultVaultOpen(recordJson: recordJson);

Future<ItemSummary> itemSummary({
  required String vaultId,
  required String recordJson,
}) => RustLib.instance.api.crateApiVaultItemSummary(
  vaultId: vaultId,
  recordJson: recordJson,
);

Future<ItemDetail> itemOpen({
  required String vaultId,
  required String recordJson,
}) => RustLib.instance.api.crateApiVaultItemOpen(
  vaultId: vaultId,
  recordJson: recordJson,
);

/// Signs a fresh WebAuthn challenge with the item's passkey and verifies it
/// with the public key, as the website would.
Future<void> itemPasskeyTest({
  required String vaultId,
  required String recordJson,
}) => RustLib.instance.api.crateApiVaultItemPasskeyTest(
  vaultId: vaultId,
  recordJson: recordJson,
);

/// The item's current one-time password, or None if it has none.
Future<OneTimeCode?> itemTotp({
  required String vaultId,
  required String recordJson,
  required PlatformInt64 unixSecs,
}) => RustLib.instance.api.crateApiVaultItemTotp(
  vaultId: vaultId,
  recordJson: recordJson,
  unixSecs: unixSecs,
);

/// Opens a project and returns its `ProjectMeta` as JSON. `member_wrap_json`
/// is `projectKey` from `GET /access/projects/:id/keys/me` for a shared project.
Future<String> projectOpen({
  required String recordJson,
  String? memberWrapJson,
}) => RustLib.instance.api.crateApiVaultProjectOpen(
  recordJson: recordJson,
  memberWrapJson: memberWrapJson,
);

Future<EnvironmentView> environmentOpen({
  required String projectId,
  required String entryJson,
  String? memberWrapJson,
}) => RustLib.instance.api.crateApiVaultEnvironmentOpen(
  projectId: projectId,
  entryJson: entryJson,
  memberWrapJson: memberWrapJson,
);

/// Opens a folder's or secret's metadata. `kind` is `folder` or `secret`.
Future<String> entryOpen({
  required String projectId,
  required String kind,
  required String id,
  required String blobJson,
}) => RustLib.instance.api.crateApiVaultEntryOpen(
  projectId: projectId,
  kind: kind,
  id: id,
  blobJson: blobJson,
);

/// Decrypts one secret value to show or copy.
Future<String> secretValueOpen({
  required String projectId,
  required String secretId,
  required String environmentId,
  required String blobJson,
}) => RustLib.instance.api.crateApiVaultSecretValueOpen(
  projectId: projectId,
  secretId: secretId,
  environmentId: environmentId,
  blobJson: blobJson,
);

class EnvironmentView {
  /// `EnvironmentMeta` as JSON.
  final String metaJson;

  /// Whether this account holds the key to read values.
  final bool unlocked;

  const EnvironmentView({required this.metaJson, required this.unlocked});

  @override
  int get hashCode => metaJson.hashCode ^ unlocked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnvironmentView &&
          runtimeType == other.runtimeType &&
          metaJson == other.metaJson &&
          unlocked == other.unlocked;
}

/// Everything in a login item, for the detail screen.
class ItemDetail {
  final String title;
  final String username;
  final String password;
  final List<String> urls;
  final String notes;
  final bool hasTotp;
  final PasskeyDetail? passkey;

  const ItemDetail({
    required this.title,
    required this.username,
    required this.password,
    required this.urls,
    required this.notes,
    required this.hasTotp,
    this.passkey,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      username.hashCode ^
      password.hashCode ^
      urls.hashCode ^
      notes.hashCode ^
      hasTotp.hashCode ^
      passkey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ItemDetail &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          username == other.username &&
          password == other.password &&
          urls == other.urls &&
          notes == other.notes &&
          hasTotp == other.hasTotp &&
          passkey == other.passkey;
}

/// What the item list shows. The password stays in Rust.
class ItemSummary {
  final String title;
  final String username;
  final String? url;
  final bool hasTotp;
  final bool hasPasskey;

  const ItemSummary({
    required this.title,
    required this.username,
    this.url,
    required this.hasTotp,
    required this.hasPasskey,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      username.hashCode ^
      url.hashCode ^
      hasTotp.hashCode ^
      hasPasskey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ItemSummary &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          username == other.username &&
          url == other.url &&
          hasTotp == other.hasTotp &&
          hasPasskey == other.hasPasskey;
}

class OneTimeCode {
  final String code;
  final int period;

  /// Seconds until the next code.
  final int remaining;

  const OneTimeCode({
    required this.code,
    required this.period,
    required this.remaining,
  });

  @override
  int get hashCode => code.hashCode ^ period.hashCode ^ remaining.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneTimeCode &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          period == other.period &&
          remaining == other.remaining;
}

/// An item's passkey without its private key, which stays in Rust.
class PasskeyDetail {
  /// The website's domain, such as `github.com`.
  final String rpId;
  final String userName;
  final String credentialId;

  /// Base64url SubjectPublicKeyInfo.
  final String publicKey;

  /// Unix seconds.
  final PlatformInt64 createdAt;

  const PasskeyDetail({
    required this.rpId,
    required this.userName,
    required this.credentialId,
    required this.publicKey,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      rpId.hashCode ^
      userName.hashCode ^
      credentialId.hashCode ^
      publicKey.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PasskeyDetail &&
          runtimeType == other.runtimeType &&
          rpId == other.rpId &&
          userName == other.userName &&
          credentialId == other.credentialId &&
          publicKey == other.publicKey &&
          createdAt == other.createdAt;
}

class VaultSummary {
  final String id;
  final String name;

  const VaultSummary({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}
